spring:
  datasource:
    url: jdbc:mysql://120.27.157.8:3306/lvtest1
    username: root
    password: nosFMiGCARhB4oxu
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations:
  classpath*:com/bd/basesync/mapper/*.xml
  type-aliases-package: com.bd.basesync.entity